name = "dartdublin-gtfs"
main = "src/index.ts"
compatibility_date = "2025-10-31"


routes = [
  { pattern = "dartdublin-gtfs-api-endpoint.kgans.com/*", zone_name = "kgans.com" }
]

r2_buckets = [
  { binding = "DATA", bucket_name = "dartdublin-gtfs" }
]

[observability]
enabled = true
