name = "dartdublin-gtfs-api"
main = "src/index.js"
compatibility_date = "2025-10-31"

routes = [
  { pattern = "dartdublin-gtfs-api-endpoint.kgans.com/*", zone_name = "kgans.com" }
]

r2_buckets = [
  { binding = "GTFS_R2", bucket_name = "dartdublin-gtfs" }
]
