name = "dartdublin-data"
main = "src/worker.mjs"
compatibility_date = "2025-10-30"
workers_dev = false
preview_urls = false

routes = [
  { pattern = "dartdublin-gtfs-api-endpoint.kgans.com/*", zone_name = "kgans.com" }
]

[[r2_buckets]]
binding = "DATA"
bucket_name = "dartdublin-gtfs"
