name = "dartdublin-gtfs-api"
main = "src/index.ts"
compatibility_date = "2025-10-31"
workers_dev = false

routes = [
  { pattern = "dartdublin-gtfs-api-endpoint.kgans.com/*", zone_name = "kgans.com" }
]

[[r2_buckets]]
binding = "GTFS"
bucket_name = "dartdublin-gtfs"
